# ? MY_NAME
# : plugin:
#     id: wev-echo
#     value: Bobby Pringles

MY_NAME:
  plugin:
    id: wev-echo
    value: Bobby Pringles

# - set: MY_FLAVOR
#   handler:
#     id: wev-echo
#     value: Spicy

# ? - AWS_ACCESS_KEY_ID
#   - AWS_SECRET_ACCESS_KEY
#   - AWS_SESSION_TOKEN
# : plugin:
#     id: wev-awsmfa

[AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN]:
  plugin:
    id: wev-awsmfa
