copyright: Copyright &copy; 2021 Cariad Eccleston. Released under the MIT
           Licence.

edit_uri: blob/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cariad/wev
      name: wev on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cariadeccleston
      name: Cariad Eccleston on Twitter

site_name: "wev: with environment variables"
theme:
  favicon: favicon.png
  features:
    - navigation.instant
    - navigation.tabs
  font:
    code: Fira Code
    text: Rubik
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    primary: indigo

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: "#"
nav:
  - Getting started:
      - index.md
      - installation.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - Licence: LICENSE.md
  - Configuration:
      - configuration/index.md
      - configuration/schema.md
      - configuration/directories.md
      - configuration/filenames.md
  - Examples:
      - examples/awsmfa.md
      - examples/aws-profile-per-project.md
  - Plugins:
      - plugins/index.md
      - plugins/wev-echo.md
  - Create a plugin:
      - Introduction: create-a-plugin/index.md
      - Preparation: create-a-plugin/preparation.md
      - Create plugin.py: create-a-plugin/plugin.py.md
      - Create __init.py__: create-a-plugin/init.py.md
      - Create setup.py: create-a-plugin/setup.py.md
      - Code summary: create-a-plugin/code-summary.md
      - Testing: create-a-plugin/testing.md
plugins:
  - git-revision-date
  - search
repo_url: https://github.com/cariad/wev
