name: wev

on:  # yamllint disable-line rule:truthy
  - push

jobs:

  build:
    container: cariad/ci:1.3.0
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: cache-venv
        name: Get cached virtual environment
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-venv-${{ hashFiles('Pipfile.lock') }}
          path: ~/.local/share/virtualenvs

      - if: steps.cache-venv.outputs.cache-hit != 'true'
        name: Create virtual environment
        run: pipenv sync --dev

      - name: Build
        run: pipenv run ./build.sh "${GITHUB_REF##*/}"

      - name: Archive distributable
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: dist
          retention-days: 1

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: site
          retention-days: 1


  test_code:
    container: cariad/ci:1.3.0
    if: startsWith(github.ref, 'refs/head')
    name: Test code
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: cache-venv
        name: Get cached virtual environment
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-venv-${{ hashFiles('Pipfile.lock') }}
          path: ~/.local/share/virtualenvs

      - if: steps.cache-venv.outputs.cache-hit != 'true'
        name: Create virtual environment
        run: pipenv sync --dev

      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Install distributable
        run: pipenv run pip install "$(ls *.whl)"

      - name: Test
        run: pipenv run ./test.sh

      - name: Publish test coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true


  test_docs:
    container: cariad/ci:1.3.0
    if: startsWith(github.ref, 'refs/head')
    name: Test documentation
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download built documentation
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Test
        run: |
          htmlproofer .              \
            --allow-hash-href        \
            --check-favicon          \
            --check-html             \
            --check-img-http         \
            --check-opengraph        \
            --disable-external       \
            --report-invalid-tags    \
            --report-missing-names   \
            --report-script-embeds   \
            --report-missing-doctype \
            --report-eof-tags        \
            --report-mismatched-tags \


  test_cli:
    if: startsWith(github.ref, 'refs/head')
    name: Test CLI (Python ${{ matrix.python-version }})
    needs: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Install distributable
        run: pip install "$(ls *.whl)"

      - name: Assert version
        run: |
          wev --version | tee version.tmp
          grep -qF "${GITHUB_REF##*/}" version.tmp


  publish_documentation:
    container: cariad/ci:1.3.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      S3_PATH: s3://wevcliapp-bucket-1hhoffdc0ib9x
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - test_cli
      - test_docs
    runs-on: ubuntu-20.04
    steps:
      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Publish
        run: aws s3 sync --delete . ${S3_PATH:?}


  publish_to_github:
    if: startsWith(github.ref, 'refs/tags')
    name: Publish to GitHub release
    needs:
      - test_cli
      - test_docs
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Get path to distributable
        run: echo "DISTRIBUTABLE=$(ls *.whl)" >> $GITHUB_ENV

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/x-wheel+zip
          asset_name: ${{ env.DISTRIBUTABLE }}
          asset_path: ${{ env.DISTRIBUTABLE }}
          upload_url: ${{ steps.get_release.outputs.upload_url }}


  publish_to_pypi:
    if: startsWith(github.ref, 'refs/tags')
    name: Publish to PyPI
    needs:
      - test_cli
      - test_docs
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
