name: wev

on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - "**"
    tags:
      - "**"

jobs:

  publish_documentation:
    container: cariad/ci:1.2.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      S3_PATH: s3://wevcliapp-bucket-1hhoffdc0ib9x
    needs: test_cli
    runs-on: ubuntu-20.04
    steps:
      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
      - name: Publish
        run: aws s3 sync --delete . ${S3_PATH:?}


  publish_to_github:
    name: Publish to GitHub release
    needs: test_cli
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Get path to distributable
        run: echo "DISTRIBUTABLE=$(ls *.whl)" >> $GITHUB_ENV

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/x-wheel+zip
          asset_name: ${{ env.DISTRIBUTABLE }}
          asset_path: ${{ env.DISTRIBUTABLE }}
          upload_url: ${{ steps.get_release.outputs.upload_url }}


  publish_to_pypi:
    name: Publish to PyPI
    needs: test_cli
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
